server:
  port: 8081
  ssl:
    enabled: false

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Moscow
  application:
    name: payroll-master
  datasource:
    url: jdbc:postgresql://db:5432/payroll
    username: payroll
    password: payroll
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
    default-schema: payroll
jwt:
  key: ${JWT_KEY}
  access-token-expiration: 28800000
